# Generated by Django 4.2.4 on 2023-10-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(verbose_name='slug')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('date_of_creation', models.DateField(max_length=100, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(verbose_name='публикация')),
                ('views', models.IntegerField(verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
