# Generated by Django 4.2.4 on 2023-10-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image_alter_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, max_length=100, verbose_name='Дата создания'),
        ),
    ]
